In [1]:
import pandas as pd
import numpy as np

In [2]:
# 非智能合约所有交易记录
transaction = pd.read_excel("transaction.xlsx")
transaction

,trans_hash,blockNumber,from_balances,Froms,gas,gasPrice,input,nonce,Tos,Amount,to_balances
0,0x29671856da39b999d3449c34a12861225c634c37df6f...,9191491,523016731488273024,0x7bEED30332656CA4220CB2ce8E4508fb18013E8d,21000,2424000002,0x,558,0xe82A101121bA4488d62aFDf9a1b5E0dEBbbCdA18,3.000000e+18,0
1,0x943bc0970da19a088fbb57eb738bdbe5ae30ea03443b...,6865931,1770460000000000,0x00004f827fF296F698F04093FF899233A48fB5C5,21000,6000000000,0x,0,0x18365A89E092CCC31d2A49ab5CB697564Ec81bCF,5.200000e+16,0
2,0x1e81f7af982fd5ad29315299f648367391a680db525b...,3938126,321644369640702016,0x0004f896ed610f1D67DeD75b3C613Df2D3dd13C4,21000,21768734821,0x,0,0x905475CbcA398e8Fee6E35bCb2f530a3474B78Ce,2.499543e+18,0
3,0x68b0e08c73357d346d2d2a5a79dd6a043b8b77f1c486...,10975844,0,0x0011538e3D30A740FbAdd4e44dBBB21E6fD95299,21000,110000000000,0x,0,0x7cACAea4a2126818A1f2A3EbBBfCE3b0E5480318,1.332505e+17,0
4,0x1172a0a22b23efe7c0d7dcab2487d91d483449db395a...,5235945,0,0x0012578966E30F29c8f4a3DA751D63BA216383bf,21000,5000000000,0x,0,0xa8B3C9C2A45d68EB435b5F3eF6712FA50CDbd996,5.086935e+17,0
...,...,...,...,...,...,...,...,...,...,...,...
401740,0x60dc2dc69a2d36a6c4d507b00892f60a2b8689cf7c80...,5393397,2567833715494500171776,0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5,50000,1000000000,0x,6270259,0x179bAb8B913D057566325582daA217bef8A76966,2.080690e+17,4435300157143160
401741,0x2b597f77f3100197673b53da6ba2de81bf329b1a34d1...,5578130,769363998687975040,0x681171BEdCc9574916475CC98547288c75b1badE,940000,6000000000,0x,6602,0x179bAb8B913D057566325582daA217bef8A76966,5.000000e+18,4435300157143160
401742,0x40fd5470a844de28a3548a13e2d1391627a6b8354ba5...,5568970,2567833715494500171776,0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5,50000,1000000000,0x,6894553,0x179bAb8B913D057566325582daA217bef8A76966,2.012946e+17,4435300157143160
401743,0x7f3ec84918e4e7728d83f237ab9852e2b97024e3ad80...,5567418,2567833715494500171776,0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5,50000,1000000000,0x,6888390,0x179bAb8B913D057566325582daA217bef8A76966,2.176668e+17,4435300157143160
401744,0x305bf621c1c099ee1421b47be2781342282428654fe2...,5564562,2567833715494500171776,0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5,50000,1000000000,0x,6878753,0x179bAb8B913D057566325582daA217bef8A76966,2.016991e+17,4435300157143160

In [3]:
# 实验所用的交易记录在30-100的账户信息
address = pd.read_excel("address.xlsx")
address

                                          adress  Txncount  label
0     0xe0e1df65a64c5ae18b86463e30e96d1a657e42c4       100      1
1     0x9205ddb511303ab460698085fdaac7a81cbd93d4       100      1
2     0x39d80d7de4345821b6691ee6d71347323a8178c9       100      1
3     0x91af8014a7f74ab1cf1eedb0aa96f58dced95f38        99      1
4     0x84d2a64cf2c0b1b4a65925dc0b1a20f42fe6104f        99      1
...                                          ...       ...    ...
1142  0xD31728FD8B4Ba649502e872D33849522821CB69e        99      0
1143  0x6261F012fB3EDd3510736a486B0108ccCb97Bc92        99      0
1144  0xB516137b075770b0f99b75017ae8DB34E3602307       100      0
1145  0x500D7AE3dBEe4CbA494e2683Ad2e6fC6F21F0c06       100      0
1146  0x7D744F6a22e63D370015991Aae331F53e43aA09E       100      0

[1147 rows x 3 columns]

In [4]:
froms = list(transaction['Froms'])
tos = list(transaction['Tos'])
account = list(address['adress'])
account[1]

'0x9205ddb511303ab460698085fdaac7a81cbd93d4'

In [5]:
froms_new = [i.lower() for i in froms]
tos_new = [i.lower() for i in tos]
account_new = [i.lower() for i in account]
transaction['froms_new'] = froms_new
transaction['tos_new'] = tos_new
transaction

,trans_hash,blockNumber,from_balances,Froms,gas,gasPrice,input,nonce,Tos,Amount,to_balances,froms_new,tos_new
0,0x29671856da39b999d3449c34a12861225c634c37df6f...,9191491,523016731488273024,0x7bEED30332656CA4220CB2ce8E4508fb18013E8d,21000,2424000002,0x,558,0xe82A101121bA4488d62aFDf9a1b5E0dEBbbCdA18,3.000000e+18,0,0x7beed30332656ca4220cb2ce8e4508fb18013e8d,0xe82a101121ba4488d62afdf9a1b5e0debbbcda18
1,0x943bc0970da19a088fbb57eb738bdbe5ae30ea03443b...,6865931,1770460000000000,0x00004f827fF296F698F04093FF899233A48fB5C5,21000,6000000000,0x,0,0x18365A89E092CCC31d2A49ab5CB697564Ec81bCF,5.200000e+16,0,0x00004f827ff296f698f04093ff899233a48fb5c5,0x18365a89e092ccc31d2a49ab5cb697564ec81bcf
2,0x1e81f7af982fd5ad29315299f648367391a680db525b...,3938126,321644369640702016,0x0004f896ed610f1D67DeD75b3C613Df2D3dd13C4,21000,21768734821,0x,0,0x905475CbcA398e8Fee6E35bCb2f530a3474B78Ce,2.499543e+18,0,0x0004f896ed610f1d67ded75b3c613df2d3dd13c4,0x905475cbca398e8fee6e35bcb2f530a3474b78ce
3,0x68b0e08c73357d346d2d2a5a79dd6a043b8b77f1c486...,10975844,0,0x0011538e3D30A740FbAdd4e44dBBB21E6fD95299,21000,110000000000,0x,0,0x7cACAea4a2126818A1f2A3EbBBfCE3b0E5480318,1.332505e+17,0,0x0011538e3d30a740fbadd4e44dbbb21e6fd95299,0x7cacaea4a2126818a1f2a3ebbbfce3b0e5480318
4,0x1172a0a22b23efe7c0d7dcab2487d91d483449db395a...,5235945,0,0x0012578966E30F29c8f4a3DA751D63BA216383bf,21000,5000000000,0x,0,0xa8B3C9C2A45d68EB435b5F3eF6712FA50CDbd996,5.086935e+17,0,0x0012578966e30f29c8f4a3da751d63ba216383bf,0xa8b3c9c2a45d68eb435b5f3ef6712fa50cdbd996
...,...,...,...,...,...,...,...,...,...,...,...,...,...
401740,0x60dc2dc69a2d36a6c4d507b00892f60a2b8689cf7c80...,5393397,2567833715494500171776,0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5,50000,1000000000,0x,6270259,0x179bAb8B913D057566325582daA217bef8A76966,2.080690e+17,4435300157143160,0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5,0x179bab8b913d057566325582daa217bef8a76966
401741,0x2b597f77f3100197673b53da6ba2de81bf329b1a34d1...,5578130,769363998687975040,0x681171BEdCc9574916475CC98547288c75b1badE,940000,6000000000,0x,6602,0x179bAb8B913D057566325582daA217bef8A76966,5.000000e+18,4435300157143160,0x681171bedcc9574916475cc98547288c75b1bade,0x179bab8b913d057566325582daa217bef8a76966
401742,0x40fd5470a844de28a3548a13e2d1391627a6b8354ba5...,5568970,2567833715494500171776,0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5,50000,1000000000,0x,6894553,0x179bAb8B913D057566325582daA217bef8A76966,2.012946e+17,4435300157143160,0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5,0x179bab8b913d057566325582daa217bef8a76966
401743,0x7f3ec84918e4e7728d83f237ab9852e2b97024e3ad80...,5567418,2567833715494500171776,0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5,50000,1000000000,0x,6888390,0x179bAb8B913D057566325582daA217bef8A76966,2.176668e+17,4435300157143160,0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5,0x179bab8b913d057566325582daa217bef8a76966
401744,0x305bf621c1c099ee1421b47be2781342282428654fe2...,5564562,2567833715494500171776,0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5,50000,1000000000,0x,6878753,0x179bAb8B913D057566325582daA217bef8A76966,2.016991e+17,4435300157143160,0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5,0x179bab8b913d057566325582daa217bef8a76966

In [6]:
# 在所有交易记录中提取记录为30-100的用户交易信息
from_trans = transaction.loc[transaction['froms_new'].isin(account_new)]
to_trans = transaction.loc[transaction['tos_new'].isin(account_new)]

In [7]:
type(from_trans)

pandas.core.frame.DataFrame

In [8]:
data = from_trans.append(to_trans)
data

,trans_hash,blockNumber,from_balances,Froms,gas,gasPrice,input,nonce,Tos,Amount,to_balances,froms_new,tos_new
1738,0xdcf3187e2c7e0a4fc7a1d93d50913f5c43ba68e24e04...,6255810,685000000000000,0x164911c2B21319007C46537D12B54bD2c8A51254,21000,41000000000,0x,13,0xB3bf9e759C859a63176FEaA2244517b2C9309EDB,5.239473e+17,0,0x164911c2b21319007c46537d12b54bd2c8a51254,0xb3bf9e759c859a63176feaa2244517b2c9309edb
23479,0x3a3f6c867b842f703937fca474ff79ed82f2fea365e1...,5762706,0,0xF6884686a999f5ae6c1AF03DB92BAB9c6d7DC8De,21000,99000000000,0x,4,0xae995C1A9983dC8AC4ce7f3e558F9C6997E0C1a7,2.000000e+18,848278000000000000,0xf6884686a999f5ae6c1af03db92bab9c6d7dc8de,0xae995c1a9983dc8ac4ce7f3e558f9c6997e0c1a7
23480,0xa85fd194d277bd2d2d3845a1e7dbde04a81ffdf6a9ee...,10700788,0,0xF6884686a999f5ae6c1AF03DB92BAB9c6d7DC8De,21000,288000000000,0x,25,0xDf9191889649C442836ef55De5036a7b694115b6,4.460856e+20,0,0xf6884686a999f5ae6c1af03db92bab9c6d7dc8de,0xdf9191889649c442836ef55de5036a7b694115b6
23481,0x2dbe1f701a04a7672fabff74d618de327e643b2d88b3...,10700765,0,0xF6884686a999f5ae6c1AF03DB92BAB9c6d7DC8De,21000,288000000000,0x,24,0xDf9191889649C442836ef55De5036a7b694115b6,1.000000e+21,0,0xf6884686a999f5ae6c1af03db92bab9c6d7dc8de,0xdf9191889649c442836ef55de5036a7b694115b6
23482,0x827ee54947c6a81a413b4a5cd31b4743745efca4b8aa...,10699833,0,0xF6884686a999f5ae6c1AF03DB92BAB9c6d7DC8De,21000,288000000000,0x,23,0xDf9191889649C442836ef55De5036a7b694115b6,1.000000e+21,0,0xf6884686a999f5ae6c1af03db92bab9c6d7dc8de,0xdf9191889649c442836ef55de5036a7b694115b6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
273065,0x2af92c11aa5c57b8cf053ecabc08f45ffc995bb3744c...,4277388,59667074107464096,0xd94c9ff168dc6aEbf9b6CC86dEfF54f3fb0AFC33,90000,50000000000,0x,373097,0x79670903c85fA8136f9F18EE003023B6DDF0bEB4,3.165896e+17,930953568760115968,0xd94c9ff168dc6aebf9b6cc86deff54f3fb0afc33,0x79670903c85fa8136f9f18ee003023b6ddf0beb4
273066,0x9ca4ce83a5f954dfb6f085493845894839ed6422dd96...,4272300,104425328244444992,0xA1a74107ec5252363A248645C3E143AAa8a5669E,25201,1000000000,0x,17,0x79670903c85fA8136f9F18EE003023B6DDF0bEB4,1.000000e+19,930953568760115968,0xa1a74107ec5252363a248645c3e143aaa8a5669e,0x79670903c85fa8136f9f18ee003023b6ddf0beb4
273068,0x02ca2e8d909dc7ed54d4d6a902b9ced562c8f5ee9fb2...,4245096,2540198576404940,0x6E779a512B35E116a83eD0C0757f8C0FBd942f56,90000,50000000000,0x,19076,0x79670903c85fA8136f9F18EE003023B6DDF0bEB4,1.999730e+19,930953568760115968,0x6e779a512b35e116a83ed0c0757f8c0fbd942f56,0x79670903c85fa8136f9f18ee003023b6ddf0beb4
273069,0x607a6a733902f916e6a4a66f940defd792d4b597f659...,4240763,2540198576404940,0x6E779a512B35E116a83eD0C0757f8C0FBd942f56,90000,24664144555,0x,3708,0x79670903c85fA8136f9F18EE003023B6DDF0bEB4,1.999730e+19,930953568760115968,0x6e779a512b35e116a83ed0c0757f8c0fbd942f56,0x79670903c85fa8136f9f18ee003023b6ddf0beb4
377637,0xab9d2df7d761b7f8de48f01ffdf5f04aae4bd3c96e69...,11563799,29251880000000000,0x4fBdF7fB3b94DAC6eF095C0d2572d7c1d05ebCF6,21000,51000001459,0x,251,0x12227DFe5363cbE55919e230653810de0fF317e2,1.024691e+17,447077118656206976,0x4fbdf7fb3b94dac6ef095c0d2572d7c1d05ebcf6,0x12227dfe5363cbe55919e230653810de0ff317e2

In [9]:
data.loc[data['to_balances']=='None', 'to_balances'] = 0
data.loc[data['from_balances']=='None', 'from_balances'] = 0

In [10]:
data.to_excel('data.xlsx')